export { default as UsersGridArea } from "./components/UsersGridArea";
export { default as ComputersGridArea }  from "./components/ComputersGridArea";
export { default as createGameBoardCoordinate } from "./createGameBoardCoordinate";
export { default as createWaterCells } from "./createWaterCells";
export { default as placeShipsInWater } from "./placeShipsInWater";
export { default as shipFactory } from "./shipFactory";
export { default as checkCellCoordinate } from "./checkCellCoordinate";
export { getShipOccupiedCellsNumbers, getShipOccupiedCellsCoordinates } from "./getShipOccupiedCells";
export { default as placeShipsInDockArea } from "./placeShipsInDockArea";
export { default as changeShipOrientation } from "./changeShipOrientation";
export { default as dragShip } from "./dragShip";
export { default as addHitOrMissMark } from "./addHitOrMissMark";